"""set nullable fields for questions

Revision ID: ce4ed380bbbb
Revises: 061b8e896d60
Create Date: 2024-11-23 07:25:40.410221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce4ed380bbbb'
down_revision: Union[str, None] = '061b8e896d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grant_questions', 'requested_amount',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grant_questions', 'grant_purpose',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grant_questions', 'prepared_documents',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grant_questions', 'patents_or_innovations',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grant_questions', 'previous_grants',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grant_questions', 'operational_regions',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grant_questions', 'business_size',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grant_questions', 'project_idea',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grant_questions', 'annual_revenue',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grant_questions', 'okved_codes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_grant_questions_requested_amount', table_name='grant_questions')
    op.create_unique_constraint(None, 'rate_limit', ['id'])
    op.create_unique_constraint(None, 'tier', ['id'])
    op.create_unique_constraint(None, 'token_blacklist', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token_blacklist', type_='unique')
    op.drop_constraint(None, 'tier', type_='unique')
    op.drop_constraint(None, 'rate_limit', type_='unique')
    op.create_index('ix_grant_questions_requested_amount', 'grant_questions', ['requested_amount'], unique=False)
    op.alter_column('grant_questions', 'okved_codes',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('grant_questions', 'annual_revenue',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('grant_questions', 'project_idea',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('grant_questions', 'business_size',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('grant_questions', 'operational_regions',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('grant_questions', 'previous_grants',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('grant_questions', 'patents_or_innovations',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('grant_questions', 'prepared_documents',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('grant_questions', 'grant_purpose',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('grant_questions', 'requested_amount',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
