"""docs_ocr_passport

Revision ID: eae5d699dd99
Revises: a2495e6ba1c1
Create Date: 2024-11-24 10:55:52.659596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae5d699dd99'
down_revision: Union[str, None] = 'a2495e6ba1c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.Uuid(), nullable=False),
    sa.Column('series', sa.String(length=4), nullable=True),
    sa.Column('number', sa.String(length=6), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('birth_place', sa.String(), nullable=True),
    sa.Column('issue_date', sa.String(), nullable=True),
    sa.Column('issuing_authority', sa.String(), nullable=True),
    sa.Column('department_code', sa.String(), nullable=True),
    sa.Column('registration_address', sa.String(), nullable=True),
    sa.Column('registration_date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passports_id'), 'passports', ['id'], unique=False)
    op.create_index(op.f('ix_passports_user_uuid'), 'passports', ['user_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passports_user_uuid'), table_name='passports')
    op.drop_index(op.f('ix_passports_id'), table_name='passports')
    op.drop_table('passports')
    # ### end Alembic commands ###
